### ISSUE TITLE
No Group Messages

### ISSUE THREAD

**Issue by shivasharmaarya** [The-ITech-Professionals/MS-TL#3]
**Describe the bug**
No group messages are showing up or for a matter of fact Groups are not showing

**To Reproduce**
Open the app and there won;t be no group chat even if someone is messaging on group chat nothing is popping out.

**Expected behavior**
Groups and Group messages should display

**Comment by ShaneOss** [comment]
Hi @shivasharmaarya,

Do you see any of group messages in the Notification History? Or the Windows Action Center?
When you say no Groups are showing, do you mean in search? Search only shows users in your organisation's Azure Active Directory.
Thanks!

**Comment by ShaneOss** [comment]
Another thing to note. If you are already engaged in a conversation and have the message window open, any incoming messages for that conversation will be displayed in the message window, and won't be displayed as an Action Center notification.
