### ISSUE TITLE
Need win7 app.

### ISSUE THREAD

**Issue by TheCloudCrafter** [The-ITech-Professionals/MS-TL#4]
**Is your feature request related to a problem? Please describe.**
I have a mixed environment with lots of Win7 virtual machines. 
We cannot load your app due to no windows store.

**Describe the solution you'd like**
Please create a win7 install of your app.

**Comment by ShaneOss** [comment]
We would love to. But unfortunately, Windows 7 is now end of life ([Jan 14 2020](https://www.microsoft.com/en-au/microsoft-365/windows/end-of-windows-7-support)), and we can’t support it for security reasons. There’s also functionality on the UI side of things that MS-TL uses, which is included with Windows 10.
Might be a good time to upgrade those VMs to mitigate any potential security risks. There’s still ways you can upgrade to Windows 10 for free. It’s important that your OS is up-to-date with the latest patches. Thanks!

**Comment by TheCloudCrafter** [comment]
We're working on it. Still updating legacy stuff.
